### PR TITLE
Added Captain Marvel and new sinergies (Spider-Gwen,She-Hulk & Gamora)

### PR DESCRIPTION
**Pull request by Luiz012**

### CODE REVIEW

**Comment by user23498723452** [comment]
@Luiz012 This incorrectly removed a lot of 2 stars.  Please restore all of them.  They were all purchasable.  I have them in my roster.

**Comment by Luiz012** [comment]
@user23498723452 I'm sorry for that. Can you list the champions that you have and aren't there?

**Comment by user23498723452** [comment]
@Luiz012 I have no idea why you are removing any champ.  Why don't you simply restore all of them?  I cannot be asked to validate my champs.  They simply are almost all part of the game.  The PHC and 2 star crystals only offer a subset of them.  Kabam has taken to selling collector style crystals for the remainder.

Please don't put the burden on me to validate this AFTER I already input all of them.  That isn't fair to me.  You can go and review my pull requests if you need to.  I'm not here to post screenshots of my roster.

**Comment by Luiz012** [comment]
@user23498723452  i'm not putting the burden on you, i removed some of them because i didn't find anyone that has them on their roster ( and i searched a lot before of doing that). 
I use this tool to keep track of my collection, I don't wanna be looking for some champs that don't even exist.
That's why I'm asking you the ones that you have, so i can put them back there.
Can you please do that?

**Comment by user23498723452** [comment]
@Luiz012  You are out of line asking anyone to prove their roster.  It doesn't matter what I post today,  because some idiot is going to try and remove them AGAIN in 6 months claiming that their tiny roster is the perfect justification to do so.

 Why are you making undocumented code changes anyway?  Why did you not clearly state that you were removing all of those 2* champs in your pull request?  Why did I have to search thru your changes to find this. 

Are you trying to commandeer this for your own personal needs? If so, you need to fork this and build your own instance.  This is intended for use by everyone.  That includes people with much larger rosters than yours, like myself.

**If you don't have over 500 unique champions,**  I strongly suggest you open the game and look at the leaderboards present in the settings (Play Games app in Android or Game Center in iOS), which will show that some well known players have over 500 unique champions.  Those leaderboards ARE ACCURATE.  Those counts come because there are 2 stars for almost every champ released.  Not because there are unknown champs out there hidden from your eyes OR because someone is fudging data.

@hook  Please make this stop.  This is ridiculous.  If you are going to let Luiz take over full control of this codebase, then I think you ought rename it to LuizRoster and hand over the repo to him.  Because that is the only person it will serve.  I'm not here to post screenshots of my roster as proof that a fucking 2* champ exists.

**Comment by hook** [comment]
We should not be removing any champs unless it can be 100% verified that it was mistakenly added previously.

**Comment by Luiz012** [comment]
I already said that I'm sorry, it will be fixed on the next update.
@user23498723462 @, there was no need to act like a douchebag, I'm not trying to rule this (there is a ton of 2* champs that I still don't have and I didn't removed them). When this champs were added in the game, I wasn't playing and the sites that I thought that were trustworthy never mentioned the existence of them. I don't care how big your roster are or who you have or don't. I was just asking you to help with that. I don't receive nothing by helping here. If you are so mad with that, go on and do a better job.

**Comment by Luiz012** [comment]
I already said that I'm sorry, it will be fixed on the next update

@user23498723452 there was no need to act like a douchebag, I'm not trying to rule this (there is a ton of 2* champs that I still don't have and I didn't removed them). When this champs were added in the game, I wasn't playing and the sites that I thought that were trustworthy never mentioned the existence of them. I don't give a fuck how big your roster are or who you have or don't. I was just asking you to help with that. I don't receive nothing by helping here. If you are so mad with that, go on and do a better job.

**Comment by user23498723452** [comment]
@Luiz012  I do apologize for my attitude, which was not really called for.  I was very frustrated with your tone that I needed to prove my roster to you.  That is a bit condescending.  Like I am lying about what is on my roster, or sold in a crystal.  Like I said, it was in my pull request from months ago.

For 2* , I think it is fairly clear that Kabam is selling almost all of them now.  I am only missing 4 that were previously showing in the app.  I know AA was sold in the last batch (so that leaves the other 3 - which I can't see until the full roster is restored).  I'll share those remaining 2*, but I suspect that all have been made available for sale.  And maybe more than that.  So we might actually have some 2* left to add. 

I would recommend taking screen shots of all the crystal sales if you wish to try and track this going forward.  Sometimes Kabam fails to clarify some restrictions in those crystals, but usually they are accurate.  If you had been doing this since you started posting here, I think you would have all the info you needed.  No need to check people's rosters.

My other issue was that **this was done without a reference in the pull request**.  I had to go poke thru the files.  That should not happen.  If it was mentioned,  I suspect that @hook  may have noticed and questioned it.  Please just document what you are doing, so this doesn't happen again.  It is a fairly standard requirement.

I do appreciate your efforts on this repo.  You've actually got the coding skill to do it, and that is appreciated.  All I can do is some minor data updates.  We've worked together in the past, we can work together in the future.

**Pull request merged**
