### PR TITLE
Added Doc Ock, Green Goblin, Spider-Man (Stark) & Vulture

### PR DESCRIPTION
**Pull request by BillyNate**
This PR contains the said champions, but I'm afraid it is not complete yet.
It does not contain the `fullsize` images and most of the synergies are missing.

According to [marvelsynergy.com](http://www.marvelsynergy.com/champions/spider-man-stark-enhanced) some new, rather complicated, synergies have been added to the game as well 😕

If there's anything else I can do, please let me know 😉

### CODE REVIEW

**Comment by hook** [comment]
Who is do cock?

**Comment by hook** [comment]
Fullsize pics are in a uigatcha folder, you have to hunt a bit, and the names are wrong. Synergies, I'll add later I'm gonna revamp for the newer complex effects that only apply to some champs.

**Comment by BillyNate** [comment]
Do Cock? 😂 
Docter Octopus, apparently 😉

**Comment by hook** [comment]
Make sure ids are letters and numbers only, no dashes or underscores, and use the same id for the images after portrait_ and fullsize_

**Comment by BillyNate** [comment]
The lowercase ids in data/ids/champions.js en lang/en.json are copied over from the `portrait_` filename,
the uppercase ids are also letters only (no special characters or spaces), but are a bit more clear to read and are the same in every file used.

**Comment by hook** [comment]
The uppercase ids are used internally in the app, the lowercase ids are used when saving and are the actual values when we reference the capitalized ones

**Comment by BillyNate** [comment]
`fullsize` images have been added! 👍

**Pull request merged**
