### PR TITLE
Improvement in translations pt-br

### PR DESCRIPTION
**Pull request by joaoissamu**

### CODE REVIEW

**Comment by hook** [comment]
This is falling at the build stage, do you having building on your end?

**Comment by joaoissamu** [comment]
Sorry man, let me check .

**Comment by hook** [comment]
If you look at https://github.com/hook/champions/pull/137/files, there are invalid `:` characters in the json definition file.

**Comment by hook** [comment]
@joaoissamu this PR still can't be merged due to compiling issues

**Comment by joaoissamu** [comment]
Sorry man, I'll fix this

**Pull request closed without merging**
