### PR TITLE
Add Killmonger guide and resize stars to fit 6 star champions

### PR DESCRIPTION
**Pull request by Luiz012**

### CODE REVIEW

**Comment by hook** [comment]
What is the point of the `ChampionPortrait.scss` update? The commit isn't descriptive about WHAT changed.

**Comment by Luiz012** [comment]
I'm sorry, I forgot to commit lol
It changes the size of stars so they can fit in 6 star champions

Em 5 de mar de 2018 2:03 PM, "Gabriel Hook" <notifications@github.com>
escreveu:

**Comment by user23498723452** [comment]
This didn't seem to work.   I've reloaded my browser.  I think my suggestion on the previous attempt is what is needed.

Looking in my browser,  it shows the star image size as 27px (natural 39x39).  and the box is 140px wide I guess.  I think we need to shrink them to 22/23px so that they fit inside the width of that box.

ChampionPortrait seems to indicate the .champion-portrait.stars.image-icon size is 19% (of width)

YEP:  We need to change the width to 15%.  Tested in Chrome.  I think some other values also need to be updated in that block.  See below.

My guess:
```
.champion-portrait
   .stars
        .image-icon {
            top: -5px;
            width: 15%;
            height: 0;
            margin-right: 1%;
            padding: 0;
            padding-top: 15%;
```
 
https://github.com/hook/champions/blob/666ffd2196c0ee20fe283246e2f38480274e072d/src/view/Champion/ChampionPortrait.scss#L269

**Comment by Luiz012** [comment]
thanks user23498723452, it helped a lot

**Pull request merged**
