### PR TITLE
A few modifications to synergies

### PR DESCRIPTION
**Pull request by nafeger**
Added a link for electra to daredevil netflix as well as from deadpool xforce back to electra.
I only have the 4* versions of these, so I don't know if they affect other levels.

### CODE REVIEW

**Comment by hook** [comment]
Use the syntax for multiple champions giving a single synergy please.

```js
    ...fromId(CHAMPION.ELEKTRA, [
        ...fromStars(3, 4, { toId: CHAMPION.WOLVERINE, effectId: EFFECT.ARMOR }),
        ...fromStars(3, 4, [ CHAMPION.DAREDEVIL, CHAMPION.DAREDEVILNETFLIX ], { effectId: EFFECT.POWER_GAIN }),
        ...fromStars(3, 4, { toId: CHAMPION.BLACKWIDOW, effectId: EFFECT.CRITICAL_DAMAGE }),
        ...fromStars(4, [ CHAMPION.DEADPOOL, CHAMPION.DEADPOOLXFORCE ], { effectId: EFFECT.PERFECT_BLOCK }),
    ]),
```

instead of 

```js
    ...fromId(CHAMPION.ELEKTRA, [
        ...fromStars(3, 4, { toId: CHAMPION.WOLVERINE, effectId: EFFECT.ARMOR }),
        ...fromStars(3, 4, { toId: CHAMPION.DAREDEVIL, effectId: EFFECT.POWER_GAIN }),
        ...fromStars(3, 4, { toId: CHAMPION.DAREDEVILNETFLIX, effectId: EFFECT.POWER_GAIN }),
        ...fromStars(3, 4, { toId: CHAMPION.BLACKWIDOW, effectId: EFFECT.CRITICAL_DAMAGE }),
        ...fromStars(4, { toId: CHAMPION.DEADPOOL, effectId: EFFECT.PERFECT_BLOCK }),
        ...fromStars(4, { toId: CHAMPION.DEADPOOLXFORCE, effectId: EFFECT.PERFECT_BLOCK }),
    ]),**
```

This will ensure that if the user has both champs on his team he will only get the synergy applied once, as it's done in game.

**Comment by nafeger** [comment]
got it, no problem.

**Comment by hook** [comment]
Look at travis check details for linting errors 🐌

**Comment by nafeger** [comment]
i planned to do that, just got stuck working at work.

**Pull request merged**
